### PR TITLE
Generate X509 v3 certificates

### PR DESCRIPTION
**Pull request by arfoll**

### CODE REVIEW

**Comment by arfoll** [comment]
2 = 3 because openssl

**Comment by neverpanic** [comment]
@arfoll It seems this breaks some of the tests. Can you take a look?

**Comment by neverpanic** [comment]
I applied

```
diff --git a/tests/unit/test_verification.cpp b/tests/unit/test_verification.cpp
index 31b9393..33a484a 100644
--- a/tests/unit/test_verification.cpp
+++ b/tests/unit/test_verification.cpp
@@ -130,7 +130,11 @@ TEST_F(VerificationTest, testSimpleCertValidationEcc)
     std::vector<X509Certificate> trustStore{*_eccRoot.get()};
     std::vector<X509Certificate> intermediateCAs{};
 
-    ASSERT_NO_THROW(_eccIntermediate->verify(trustStore, intermediateCAs));
+    try {
+        _eccIntermediate->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << e.what();
+    }
 }
 
 TEST_F(VerificationTest, testExpiredCertValidationFails)
@@ -263,7 +267,11 @@ TEST_F(VerificationTest, testChainVerificationLen1WorksEcc)
     std::vector<X509Certificate> trustStore{*_eccRoot.get()};
     std::vector<X509Certificate> intermediateCAs{*_eccIntermediate.get()};
 
-    ASSERT_NO_THROW(_eccUser->verify(trustStore, intermediateCAs));
+    try {
+        _eccUser->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << e.what();
+    }
 }
 
 TEST_F(VerificationTest, testChainVerificationFailsWithWrongIntermediate)
@@ -370,7 +378,11 @@ TEST_F(VerificationTest, testVerificationWorksWithUnusedElementsInChainParamEcc)
     std::vector<X509Certificate> intermediateCAs{*_eccIntermediate.get(), *_root1_int1.get(),
                                                  *_root1_int2.get()};
 
-    ASSERT_NO_THROW(_eccUser->verify(trustStore, intermediateCAs));
+    try {
+        _eccUser->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << e.what();
+    }
 }
 
 TEST_F(VerificationTest, testVerificationWorksWithBothRootsInTruststore)
@@ -378,9 +390,21 @@ TEST_F(VerificationTest, testVerificationWorksWithBothRootsInTruststore)
     std::vector<X509Certificate> trustStore{*_root1.get(), *_root2.get(), *_eccRoot.get()};
     std::vector<X509Certificate> intermediateCAs{};
 
-    ASSERT_NO_THROW(_root1_int1->verify(trustStore, intermediateCAs));
-    ASSERT_NO_THROW(_root2_int1->verify(trustStore, intermediateCAs));
-    ASSERT_NO_THROW(_eccIntermediate->verify(trustStore, intermediateCAs));
+    try {
+        _root1_int1->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << "root1_int1: " << e.what();
+    }
+    try {
+        _root2_int1->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << "root2_int1: " << e.what();
+    }
+    try {
+        _eccIntermediate->verify(trustStore, intermediateCAs);
+    } catch (const MoCOCrWException& e) {
+        FAIL() << "eccIntermediate: " << e.what();
+    }
 }
 
 /*
```

which prints "certificate has expired" for all certificates that relate to ECC… either one of our test certificates did in fact expire, or this change somehow changes the validation behavior of ECC certificates…

**Comment by neverpanic** [comment]
```
$ openssl x509 -noout -in tests/unit/test-certs/eccRootCertificate.pem -enddate
notAfter=Nov 29 19:44:18 2019 GMT
```
:1st_place_medal:

**Comment by neverpanic** [comment]
#50 (plus cherry-pick to openssl1.1 once merged).

**Comment by garw** [comment]
I checked the PKCS#10 spec for CSRs and it doesn't look to me as if there was such a thing as a version 3 for CSRs.

In order to preserve backwards compatibility, I will add an option to configure the used hash function for CSRs in another PR.

**Pull request closed without merging**
